from fpdf import FPDF
import datetime
import os

class PDFReport(FPDF):
    def __init__(self, target_ip, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.target_ip = target_ip
        self.scan_date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

    def header(self):
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'Automated Vulnerability Report', 0, 1, 'C')
        
        self.set_font('Arial', 'B', 10)
        self.cell(0, 10, f'Target Host: {self.target_ip}  |  Generated: {self.scan_date}', 0, 1, 'C')
        self.ln(5)
        self.line(10, 30, 200, 30)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} - Generated by CyberSec Lab Mentor', 0, 0, 'C')

def create_pdf(target_ip, analysis_text):
    print(f"📄 Generating PDF Report for {target_ip}...")
    
    try:
        pdf = PDFReport(target_ip)
        pdf.add_page()
        pdf.set_font("Arial", size=11)

        # Cleanup text
        clean_text = analysis_text.replace("❗", "[!]")
        clean_text = clean_text.replace("**", "") 
        clean_text = clean_text.replace("### ", "\n\n>> ")

        # Add to PDF
        pdf.multi_cell(0, 10, clean_text.encode('latin-1', 'replace').decode('latin-1'))

        # FOLDER SETUP: Create 'reports' directory if it doesn't exist
        output_folder = "reports"
        os.makedirs(output_folder, exist_ok=True)

        # Create filename inside the folder
        safe_ip = target_ip.replace('.', '_')
        filename = os.path.join(output_folder, f"Report_{safe_ip}.pdf")
        
        pdf.output(filename)
        print(f"✅ PDF Created Successfully: {filename}")
        return filename

    except Exception as e:
        print(f"❌ PDF ERROR: {e}")
        return None